// US carrier name normalization mapping
// Expand as needed for your use case
export const carrierNameMap: Record<string, string> = {
  "AT&T": "AT&T",
  "AT&T Mobility": "AT&T",
  "Cingular": "AT&T",
  "Cricket Wireless": "AT&T",
  "FirstNet": "AT&T",
  "T-Mobile": "T-Mobile",
  "T-Mobile US": "T-Mobile",
  "Metro by T-Mobile": "T-Mobile",
  "Sprint": "T-Mobile",
  "Boost Mobile": "T-Mobile",
  "Ultra Mobile": "T-Mobile",
  "Mint Mobile": "T-Mobile",
  "Verizon": "Verizon",
  "Verizon Wireless": "Verizon",
  "Visible": "Verizon",
  "TracFone": "Verizon",
  "UScellular": "UScellular",
  "Google Fi": "Google Fi",
  "Dish Wireless": "Dish",
  "Boost Infinite": "Dish",
  "GCI Wireless": "GCI",
  "C Spire": "C Spire",
  "Appalachian Wireless": "Appalachian Wireless",
  "Cellcom": "Cellcom",
  "Viaero Wireless": "Viaero Wireless",
  "Union Wireless": "Union Wireless",
  "Inland Cellular": "Inland Cellular",
  "Carolina West Wireless": "Carolina West Wireless",
  "Pine Cellular": "Pine Cellular",
  "Nex-Tech Wireless": "Nex-Tech Wireless",
  "Southern Linc": "Southern Linc",
  "Redzone Wireless": "Redzone Wireless",
  "Rock Wireless": "Rock Wireless"
};
